### ISSUE TITLE
error CS0433: The type 'ZipFile' exists in both 'Ionic.Zip.Unity

### ISSUE THREAD

**Issue by Thane5** [Plattar/gltf-exporter#10] opened 2021-03-05 11:21 UTC
I installed the asset over the unitypackage, the new toolbar item is missing and i get two errors: 

`Assets\PlattarExporter\UnityGLTF\Scripts\GLTFUtils.cs(191,3): error CS0433: The type 'ZipFile' exists in both 'Ionic.Zip.Unity, Version=1.9.1.9000, Culture=neutral, PublicKeyToken=null' and 'Ionic.Zip, Version=1.9.1.8, Culture=neutral, PublicKeyToken=edbe51ad942a3f5c'
`
`Assets\PlattarExporter\UnityGLTF\Scripts\GLTFUtils.cs(191,3): error CS0433: The type 'ZipFile' exists in both 'Ionic.Zip.Unity, Version=1.9.1.9000, Culture=neutral, PublicKeyToken=null' and 'Ionic.Zip, Version=1.9.1.8, Culture=neutral, PublicKeyToken=edbe51ad942a3f5c'
`

I'm on windows 10 and my Unity version is 2020.2.2f1

**Comment by primaryobjects** [comment] 2021-04-23 14:03
I've found the solution to this:

1. Drag & drop the unitypackage into your `Assets` folder in Unity.
2. In the dialog **Import Unity Package**, uncheck the option **Ionic.Zip.Unity.dll**.
3. Click **Import**.

![Screenshot from 2021-04-23 09-51-45](https://user-images.githubusercontent.com/529049/115882694-003cf800-a41b-11eb-96da-f792573df271.png)

*The issue is that the dll already exists in the latest version, so it is no longer needed in the unitypackage.*

**Comment by DavidArayan** [comment] 2022-12-14 23:42
this should be fixed in latest release [1.142.0](https://github.com/Plattar/gltf-exporter/releases/tag/1.142.0)

**Closed as completed by DavidArayan** 2022-12-14 23:42 UTC
